#!/bin/bash
# ==============================================================================
#
#          FILE: notifier.sh
# 
#         USAGE: ./notifier.sh
# 
#   DESCRIPTION: A simple notification script that monitors an alert file for
#                new lines and sends them as messages to a specified
#                Telegram chat via the Telegram Bot API.
# 
#     DEPENDS: curl, tail
# 
# ==============================================================================

# --- Configuration ---
# The log file generated by monitor.sh, which this script will watch for alerts.
ALERT_FILE="alerts.log"
# The configuration file containing the Telegram Bot API credentials.
# This file should be in .gitignore and not committed to version control.
CONFIG_FILE="telegram.conf"

# --- Initialization ---

# Check if the configuration file exists and source it to load the variables.
# The `source` command executes the file in the current shell.
if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
else
    echo "Configuration file '$CONFIG_FILE' not found. Please create it."
    exit 1
fi

# Check if the necessary variables have been loaded from the config file.
if [ -z "$BOT_TOKEN" ] || [ -z "$CHAT_ID" ]; then
    echo "BOT_TOKEN or CHAT_ID is not set in '$CONFIG_FILE'. Exiting."
    exit 1
fi

# --- Main Functions ---

#
# Sends a message to the Telegram API using curl.
#
# @param $1 - The message string to be sent.
#
send_telegram_notification() {
    local message="$1"
    # The official URL for the Telegram Bot API's sendMessage method.
    local url="https://api.telegram.org/bot${BOT_TOKEN}/sendMessage"

    # Use curl to send the HTTP POST request to the Telegram API.
    #   -s: Silent mode, hides progress meter.
    #   -X POST: Specifies that this is a POST request.
    #   --data-urlencode: Ensures the message text is properly URL-encoded,
    #                     so special characters don't break the request.
    #   > /dev/null: Redirects the output from Telegram (a JSON response)
    #                to nowhere, as we don't need to see it.
    curl -s -X POST "$url" --data-urlencode "chat_id=${CHAT_ID}" --data-urlencode "text=${message}" > /dev/null

    # For local logging, confirming that a notification was dispatched.
    echo "Telegram notification sent at $(date): ${message}"
}

# --- Main Execution ---

echo "Starting Telegram notifier..."
# Send a startup message to confirm the notifier script is running correctly.
send_telegram_notification "Notifier service started on $(hostname) at $(date)"

# The core of the script. This command continuously watches the ALERT_FILE.
# `tail -n 0 -F` is a robust way to follow a file:
#   -n 0: Starts reading from the end of the file (doesn't process old alerts).
#   -F: "Follow" mode, which handles file rotation (when log files are renamed
#       and a new one is created).
# The output of tail (each new line) is piped into the `while` loop.
tail -n 0 -F "$ALERT_FILE" | while read -r line
do
    # Check if the line is not empty before sending.
    if [ -n "$line" ]; then
        send_telegram_notification "$line"
    fi
done
